"""Add fields to Application

Revision ID: 14b4138bf5e1
Revises: 
Create Date: 2025-07-21 15:31:10.013291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14b4138bf5e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('resume_id', sa.Integer(), nullable=True))
    op.add_column('applications', sa.Column('status', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('applied_at', sa.DateTime(), nullable=True))
    op.add_column('applications', sa.Column('notes', sa.String(), nullable=True))
    op.create_foreign_key(None, 'applications', 'resumes', ['resume_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_column('applications', 'notes')
    op.drop_column('applications', 'applied_at')
    op.drop_column('applications', 'status')
    op.drop_column('applications', 'resume_id')
    # ### end Alembic commands ###
