"""update_job_and_application_schema

Revision ID: 87c34fc946a3
Revises: b9a021d683fa
Create Date: 2025-07-27 14:12:32.083454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87c34fc946a3'
down_revision: Union[str, Sequence[str], None] = 'b9a021d683fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('work_type', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('category', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('posted_date', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('method', sa.String(), nullable=True))
    op.drop_column('jobs', 'job_category')
    op.drop_column('jobs', 'job_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('job_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('job_category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('jobs', 'method')
    op.drop_column('jobs', 'posted_date')
    op.drop_column('jobs', 'category')
    op.drop_column('jobs', 'work_type')
    # ### end Alembic commands ###
